language: python
cache: pip
python:
  - "3.6"
environment: 
  - conda env create -f environment.yml
install:
  - pip install -r requirements.txt
script:
  - tableauExtension/tests/test_create_extract.py
